config/routes.rb
OpenDocket::Application.routes.draw do

  get "activities/new"

  get "notices/new"

  get "submissions/new"

  get "action_item_meeting/new"

  get "action_meetings/new"

  get "attendance_texts/new"

  resources :people do
    resources :memberships
  end
  
  get "meeting_texts/new"

  get "statuses/new"

  get "user/new"

  get "status/new"

  get "attachments/new"

  resources :aktions 

  resources :memberships

  resources :notices

  resources :items do 
    resources :activities
    resources :dockets
    resources :documents
    resources :item_meetings
    resources :statuses
  end
 
  resources :committees do
    resources :dockets
    resources :meetings
    resources :memberships
  end

  resources :documents do
    resources :attachments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites do
    resources :rooms
  end

  resources :meetings do
    resources :aktions
    resources :attendance_texts
    resources :committee_meetings
    resources :documents
    resources :item_meetings
    resources :meeting_texts
    resources :notices
    resources :statuses
  end

  resources :dockets do
    resources :statuses
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/committees/:id/edit' => 'committees#edit', :via => :post
  match '/items/:id/edit' => 'items#edit', :via => :post
  match '/meetings/:id/agenda' => 'meetings#agenda', :as => 'meeting_agenda', :via => :get
  match '/meetings/:id/public_hearing_notice' => 'meetings#public_hearing_notice', :as => 'meeting_public_hearing_notice', :via => :get
  match '/meetings/:id/report' => 'meetings#report', :as => 'meeting_report', :via => :get  
 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'item_meetings/reorder' => 'item_meetings#reorder', :as => 'item_meetings_reorder', :via => :get
  match 'action_meetings/reorder' => 'action_meetings#reorder', :as => 'action_meetings_reorder', :via => :get

end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id           :integer          not null, primary key
#  committee_id :integer
#  person_id    :integer
#  term_start   :date
#  term_end     :date
#  display_as   :string(255)
#  position     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  creator_id   :integer
#  updater_id   :integer
#

class Membership < ActiveRecord::Base
  attr_accessible :committee_id, :display_as, :person_id, :position, :term_end, :term_start

  # term_start needs to be validated that it doesn't fall in-between any existing start/end pair
  # for the committee/person pair. Another way to think about it: committee/person pair has to be 
  # unique for all days in the range of days.
  # Also cannot have a term_start without term_end if there is an existing row for the committee/person 
  # pair without a term_end. In other words, only one term_start/no term_end per committee/person pair 
  validates :term_start, presence: true

  #  term_end needs to be validated that it is greater than term_start
  #  validates :term_end, 
  validates :committee_id, presence: true
  validates :person_id, presence: true
  validates :display_as, presence: true, length: { minimum: 5 }
  validates :creator_id, presence: true

  belongs_to :committee
  belongs_to :person

  belongs_to :creator, :class_name => 'User'
  belongs_to :updater, :class_name => 'User'

  # This formats term ends and adds "present" for term_end if there is no term_end date.

  def term_string
    if term_end
      term_start.strftime("%m/%d/%Y") + " - " + term_end.strftime("%m/%d/%Y")
    else
       term_start.strftime("%m/%d/%Y") + " - present"
    end
  end

  def save_with_activity
    Membership.transaction do
      activity = Activity.create!(
        :message => "#{person.name} added to #{committee.name} for the term: #{term_string}.",
        :activity_type => "PersonToCommittee", :date_actual => Date.today)

        ActivityLog.create!(:activity_id => activity.id, :owner_type => "Person", :owner_id => person_id) 
        ActivityLog.create!(:activity_id => activity.id, :owner_type => "Committee", :owner_id => committee_id)
        self.save!
    end
  end

  def update_with_activity
    Membership.transaction do
      activity = Activity.create!(
        :message => "#{person.name} assignment to #{committee.name} edited. Term: #{term_string}.",
        :activity_type => "PersonToCommittee", :date_actual => Date.today)

        ActivityLog.create!(:activity_id => activity.id, :owner_type => "Person", :owner_id => person_id) 
        ActivityLog.create!(:activity_id => activity.id, :owner_type => "Committee", :owner_id => committee_id)
        self.save!
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :admin_user,     only: [:new, :create]

  def new
   session[:return_to] = request.referer
   if params[:person_id]
     @person = Person.find(params[:person_id])
     @committees = Committee.all
   end
   if params[:committee_id]
     @committee = Committee.find(params[:committee_id])
   end
     @membership = Membership.new
  end

  def create
    @person = Person.find(params[:person_id]) 
    @committee = Committee.find_by_id(params[:membership][:committee_id])
    @membership = Membership.new(params[:membership])
    @membership.person_id = @person.id
    @membership.creator_id = current_user.id
    @membership.updater_id = current_user.id

    if @membership.save_with_activity
      flash[:success] = "You have successfully assigned #{@person.name} to the #{@committee.name}!"
      redirect_to session[:return_to] 
    else
      render 'new'
    end
  end

  def edit
    session[:return_to] = request.referer
 # For now, going to assume edit to membership will not change person.
    @committees = Committee.all
    @membership = Membership.find(params[:id])
  end

  def update
    @membership = Membership.find(params[:id])
    @membership.updater_id = current_user.id
    @membership.assign_attributes(params[:membership])
    if @membership.update_with_activity
      flash[:success] = "Successfully updated #{@membership.person.name}'s assignment to #{@membership.committee.name}"
      redirect_to session[:return_to]
    else
      render 'edit'
    end
  end


end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_membership.html.erb
<% if @person %>
  <li>
    <span class="content">
	    <%= link_to membership.committee.name, committee_path(membership.committee.id) %> (<%= membership.term_string %>)
      	    <% if current_user && current_user.admin? %>
              | <%= link_to "edit assignment", edit_membership_path(membership.id) %>
            <% end %>
    </span>
  </li>
<% else %>
  <li>
    <span class="content">
	    <%= link_to membership.display_as, person_path(membership.person.id) %> (<%= membership.term_string %>) 
      	    <% if current_user && current_user.admin? %>
              | <%= link_to "edit assignment", edit_membership_path(membership.id) %>
            <% end %>
    </span>
  </li>
    <% end %>

app/views/memberships/edit.html.erb
<% provide(:title, 'Edit Persons Membership on Committee') %>
<h1>Edit Person Membership on Committee</h1>

<div class="row">
  <div class="span6 offset3">

      <%= form_for([@membership]) do |f| %>
      <%= render :partial => 'shared/error_messages', :locals => {:object => @membership} %>

        <span>Select a committee.</span><br/>
      <% @committees.each do |committee| %>
          <%= f.radio_button :committee_id, committee.id %> <%= committee.name %><br />
      <% end %>
        <%= f.label :term_start %>
          <%= f.text_field :term_start, class: "date-picker" %>
          <%= f.label :term_end %>
          <%= f.text_field :term_end, class: "date-picker" %>
          <%= f.label :display_as%>
          <%= f.text_field :display_as %>


         <%= f.submit "Edit person membership on commitee", class: "btn btn-large btn-primary" %>
       <% end %>
  </div>
</div>

app/views/memberships/new.html.erb
<% provide(:title, 'Add Person to Committee') %>
<h1>Add Person to Committee</h1>

<div class="row">
  <div class="span6 offset3">

      <%= form_for([@person, @membership]) do |f| %>
      <%= render :partial => 'shared/error_messages', :locals => {:object => @membership} %>

        <span>Select a committee.</span><br/>
      <% @committees.each do |committee| %>
          <%= f.radio_button :committee_id, committee.id %> <%= committee.name %><br />
      <% end %>
        <%= f.label :term_start %>
          <%= f.text_field :term_start, :value => Date.today, class: "date-picker" %>
          <%= f.label :term_end %>
          <%= f.text_field :term_end, :value => Date.today, class: "date-picker" %>
          <%= f.label :display_as%>
          <%= f.text_field :display_as, :value => @person.name %>


         <%= f.submit "Add person to commitee", class: "btn btn-large btn-primary" %>
       <% end %>
  </div>
</div>