config/routes.rb
OpenDocket::Application.routes.draw do

  get "activities/new"

  get "notices/new"

  get "submissions/new"

  get "action_item_meeting/new"

  get "action_meetings/new"

  get "attendance_texts/new"

  resources :people do
    resources :memberships
  end
  
  get "meeting_texts/new"

  get "statuses/new"

  get "user/new"

  get "status/new"

  get "attachments/new"

  resources :aktions 

  resources :memberships

  resources :notices

  resources :items do 
    resources :activities
    resources :dockets
    resources :documents
    resources :item_meetings
    resources :statuses
  end
 
  resources :committees do
    resources :dockets
    resources :meetings
    resources :memberships
  end

  resources :documents do
    resources :attachments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites do
    resources :rooms
  end

  resources :meetings do
    resources :aktions
    resources :attendance_texts
    resources :committee_meetings
    resources :documents
    resources :item_meetings
    resources :meeting_texts
    resources :notices
    resources :statuses
  end

  resources :dockets do
    resources :statuses
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/committees/:id/edit' => 'committees#edit', :via => :post
  match '/items/:id/edit' => 'items#edit', :via => :post
  match '/meetings/:id/agenda' => 'meetings#agenda', :as => 'meeting_agenda', :via => :get
  match '/meetings/:id/public_hearing_notice' => 'meetings#public_hearing_notice', :as => 'meeting_public_hearing_notice', :via => :get
  match '/meetings/:id/report' => 'meetings#report', :as => 'meeting_report', :via => :get  
 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'item_meetings/reorder' => 'item_meetings#reorder', :as => 'item_meetings_reorder', :via => :get
  match 'action_meetings/reorder' => 'action_meetings#reorder', :as => 'action_meetings_reorder', :via => :get

end

app/models/meeting.rb
# == Schema Information
#
# Table name: meetings
#
#  id                  :integer          not null, primary key
#  date                :date
#  room_id             :integer
#  creator_id          :integer
#  updater_id          :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  assigner_id         :integer
#  time                :time
#  attendance_text     :text
#  agenda_submitted_by :integer
#  agenda_submitted_on :date
#  report_submitted_by :integer
#  report_submitted_on :date
#  public_hearing      :boolean
#  notice              :text
#


class Meeting < ActiveRecord::Base
  attr_accessible :creator_id, :date, :room_id, :updater_id, :committee_meetings_attributes, :time, :public_hearing, :notice

  default_scope :order => "date DESC"

  has_many :committee_meetings
  accepts_nested_attributes_for :committee_meetings, 
    :allow_destroy => true

  has_many :committees, :through => :committee_meetings

  has_many :attachments, :as => :owner
  has_many :documents, :through => :attachments, :as => :owner

  has_many :aktions

  has_many :statuses, :as => :statused
 
  has_many :item_meetings
  has_many :agendables, :through => :item_meetings

  has_many :action_meetings
  has_many :reportables, :through => :action_meetings

  has_many :action_item_meetings, :through => :item_meetings

  has_many :activity_logs, :as => :owner
  has_many :activities, :through => :activity_logs, :as => :owner

  belongs_to :room
  has_one :site, :through => :room
    
  has_one :attendance_text
  has_one :notice

  belongs_to :creator,     :class_name => 'User'
  belongs_to :updater,     :class_name => 'User'
   
  def name
    self.date.strftime("%m/%d/%y")
  end

  def self.upcoming
     all.select { |x| x['date'] >= Date.today }
  end
  
  def validate_committee
    if (self.committee_meetings.sum(:count) == 0)
      self.errors.add(:base, "A meeting must have a committee")
    end 
  end

   def committee_names_string
    committees.collect { |id| Committee.find_by_id(id).name }.join('/') 
  end

   def name_date_string
     self.committee_names_string + " (" + self.date.strftime("%m/%d/%Y") + ")"
   end

   def members_names_string
     committees.collect { |id| Committee.find_by_id(id).members_names_string }.join(', ')
   end
 
  def potential_items
    potential_items = []
    for committee in self.committees 
      potential_items = potential_items + committee.items
    end
    potential_items
  end

  def item_item_meetings
    item_meetings.all(:conditions => ["agendable_type = 'Item'"])
  end

  def items
    item_item_meetings.collect { |x| Item.find_by_id(x.agendable_id) }
  end

  def items_with_actions
    item_meetings_for_actions = action_item_meetings.collect { |x| ItemMeeting.find_by_id(x.item_meeting_id) }
    item_meetings_for_actions.select { |x| x.agendable_type = "Item" }.collect { |i| Item.find_by_id(i.agendable_id) }
  end

  def items_without_actions
    items - items_with_actions
  end

  def agenda_texts
    meeting_texts.select { |x| x['kind']=="Agenda" }
  end

  def report_texts
    meeting_texts.select { |x| x['kind']=="Report" }
  end

  def agenda_submissions
    statuses.select { |x| x['code'] == 1 }
  end

  def report_submissions
    statuses.select { |x| x['code'] == 2 }
  end

  def public_hearing_item_meetings
    item_item_meetings.select { |x| x['public_hearing'] == true }.sort_by { |y| y.position }
  end


end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update]
  before_filter :admin_user,     only: [:new, :create, :edit, :update]

  def create
    @committees = Committee.all
    @sites = Site.all
    @committee_meetings = params[:committee_meetings_attributes]
    params[:meeting][:committee_meetings_attributes] = params[:committee_meetings_attributes].map{ |x| {"committee_id" => x}}
    @meeting = Meeting.new(params[:meeting])
    @meeting.creator_id = current_user.id
    @meeting.updater_id = current_user.id
    @committee_names_string =  params[:committee_meetings_attributes].collect { |id| Committee.find_by_id(id).name }.join('/') 
# Need to put an error if no committee selected.

    if @committee_meetings
      if @meeting.save
        @activity = Activity.create(
                :message => "Created new #{@committee_names_string} meeting for #{@meeting.date.strftime("%m/%d/%y") }.",
                :activity_type => "NewMeeting", :date_actual => @meeting.created_at)
          flash[:success] = "You have succesfully created a #{@committee_names_string} meeting on #{@meeting.date.strftime("%m/%d/%y") } in #{@meeting.room.site.name}, #{@meeting.room.name}!"
        ActivityLog.create(:activity_id => @activity.id, :owner_type => "Meeting", :owner_id => @meeting.id)
        @committee_meetings.each { |i| ActivityLog.create(:activity_id => @activity.id, :owner_type => "Committee", :owner_id => i) }
        redirect_to session[:return_to] 
      else
        render 'new'
      end
    else
#      flash[:error] = "Please select a committee"
      render 'new'
    end
  end

 def edit
    @meeting = Meeting.find(params[:id])
    @sites = Site.all
    @committees = Committee.all
    @documents = @meeting.documents
  end


  def update
    @meeting = Meeting.find(params[:id])
    @meeting.updater_id = current_user.id
    @committees_to_start = @meeting.committee_meetings.map{ |x| x.committee_id }
    @committee_meetings = params[:committee_meetings_attributes]
    if @committee_meetings
      @committees_to_remove = @committees_to_start - @committee_meetings
      @committees_to_stay = @committees_to_start & @committee_meetings
      @committees_to_add = @committee_meetings - @committees_to_start
      params[:meeting][:committee_meetings_attributes] = @committees_to_add.map{ |x| {"committee_id" => x}}
      @committees_to_remove.any? do 
        @committees_to_remove.each{ |i| @meeting.committee_meetings.find_by_committee_id(i).destroy 
        @activity = Activity.create(
                :message => "Removed #{Committee.find_by_id(i).name} from #{@meeting.date.strftime("%m/%d/%y") } meeting.",
                :activity_type => "RemoveCommitteeFromMeeting", :date_actual => Date.today )
        ActivityLog.create(:activity_id => @activity.id, :owner_type => "Meeting", :owner_id => @meeting.id)
        ActivityLog.create(:activity_id => @activity.id, :owner_type => "Committee", :owner_id => i) }
     end
      if @meeting.update_attributes(params[:meeting])
        @committees_to_add.any? do
           @committees_to_add.each{ |i|
               @activity = Activity.create(
                      :message => "Added #{Committee.find_by_id(i).name} to #{@meeting.date.strftime("%m/%d/%y") } meeting.",
                      :activity_type => "RemoveCommitteeFromMeeting", :date_actual => Date.today )
               ActivityLog.create(:activity_id => @activity.id, :owner_type => "Meeting", :owner_id => @meeting.id)
               ActivityLog.create(:activity_id => @activity.id, :owner_type => "Committee", :owner_id => i) }
        end
        flash[:success] = "You have successfully updated the #{@meeting.name_date_string} meeting!"
        redirect_to @meeting
      else
        render 'edit'
      end
    else
      render 'update'
    end
  end


  def new
    session[:return_to] = request.referer
    @sites = Site.all
    @committees = Committee.all
    if params[:committee_id]
      @committee = Committee.find(params[:committee_id])
    end
    @meeting = Meeting.new
    @documents = @meeting.documents
  end

  def show
    @meeting = Meeting.find(params[:id])
    @item_meetings = @meeting.item_meetings.order('position ASC')
    @action_meetings = @meeting.action_meetings.order('position ASC')
    @documents = @meeting.documents
    @parent = @meeting
    @activities = @meeting.activities
  end

  def index
    @meetings = Meeting.all
  end

  def agenda
    @meeting = Meeting.find(params[:id])
    @parent = "agenda"
    render :layout => false
  end

  def public_hearing_notice
    @meeting = Meeting.find(params[:id])
    @parent = "agenda"
    render :layout => false
  end


  def report
    @meeting = Meeting.find(params[:id])
    @parent = "report"
    render :layout => false
  end

end

app/helpers/meetings_helper.rb
module MeetingsHelper

#  def setup_meeting(meeting)
#    (Committee.all - meeting.committees).each do |committee|
#      meeting.committee_meetings.build(:committee => committee)
#    end
#    meeting.committee_meetings.sort_by! {|x| x.committee.name }
#  end
end

app/views/meetings/_meeting.html.erb
<li>
  <span class="content">
<%#    <%= meeting.committees.collect { |committee| link_to committee.name, committee }.join("|") %>
<%#    <%= meetingtitle = meeting.committees.collect { |committee| committee.name}.join(" | ") %>
<%#    <%= meetingtitle = meetingtitle + " " + meeting.date.to_s %>
<%= link_to  meeting.date.strftime("%m/%d/%y") + " (" + meeting.time.strftime("%l:%M %p") + ")" + " -- " + meeting.committees.collect { |committee| committee.name}.join(" | ") +
  ", " + Room.find_by_id(meeting.room_id).name, meeting_path(meeting.id) %>
      <% if meeting.public_hearing %>
        (Public Hearing)
    <% end %>
</li>

app/views/meetings/_meetings.html.erb
<li>


<li>
<%-  <span class="content"><%= docket.id %></span> -%>
<%-  <span class="timestamp"> -%>
<%-    Created <%= docket.created_at %> -%>
<%-  </span> -%>
Hello world.
</li>

app/views/meetings/agenda.html.erb
<% provide(:title, @meeting.date) %>
<div class ="noprint"> <%= link_to "Back to meeting page", meeting_path(@meeting) %></div>
<div class ="title" style="text-align:center;font-weight:bold; padding-bottom:20px; width:800px;">
	<div>City of Newton</div>
<div class ="title">In Board of Alderman</div>
<div><%= @meeting.committee_names_string %> Agenda
</div>
</div>
<div style="width:800px;padding-bottom:20px;">
  <%= render @meeting.item_meetings.order('position ASC') %>
</div>
<% if @meeting.agenda_submissions.count >1 %>
  <div style="width:800px;padding-bottom:20px;">
    <div style="padding-bottom:20px;">Respectfully submitted,</div>
    <div><%= Person.find(@meeting.agenda_submissions.last.statuser_id).name %></div>
  </div>
<% end %>
<div style="width:800px;float:left">The location of this meeting is handicap accessible, and reasonable accommodations will be provided to persons requiring assistance. If you have a special accommodation need, please contact the Newton ADA Coordinator Trisha Guditz, 617 796-1156, via email at <a href="mailto:tguditz@newtonma.gov">TGuditz@newtonma.gov</a> or via TDD/TTY at 617 796-1089 at least two days in advance of the meeting date.</div>          

app/views/meetings/edit.html.erb
<% provide(:title, 'Edit Meeting') %>
<h1>Edit meeting</h1>

<div class="row">
  <div class="span6 offset3">

      <%= form_for(@meeting) do |f| %>
      <%= render :partial => 'shared/error_messages', :locals => {:object => @meeting} %>

        <div class="test">
          <%= f.label :date %>
          <%= f.text_field :date, :value => @meeting.date, class: "date-picker" %>
          <%= f.label :time %>
          <%= f.text_field :time, :value => @meeting.time.strftime("%l:%M %p") %>
          <%= f.check_box :public_hearing %> &nbsp;Public hearing
        </div>
        <br/>
        <% @sites.each do |site| %>
          <div><%= site.name %></div>
          <% site.rooms.each do |room| %>
            <%= f.radio_button :room_id, room.id %> <%= room.name %></br>
          <% end %>
        <% end %>

<%#      <%= f.fields_for :committee_meetings do |ff| %>
<%#        <%= ff.label :committee_id %>
<%#        <%= ff.text_field :committee_id %>
<%#      <% end %>

<%# This version creates a parameters array with errors. %>
<%#      <% @committees.each_with_index do |committee,idx| %>
<%#         <%= check_box_tag( "meeting[committee_meetings_attributes][#{idx}][committee_id]",committee.id) %>
<%#         <%= committee.name %>
<%#         <br/>
<%#       <% end %>
<br/>
        <div>Select a committee or committees for the meeting.</div>
        <% for committee in @committees.each %>
          <% if @meeting.committees.include?(committee) %>
             <%= check_box_tag( "[committee_meetings_attributes][]", committee.id, true) %> 
            <%= committee.name %>
          <% else %>
            <%= check_box_tag( "[committee_meetings_attributes][]", committee.id) %>
            <%= committee.name %>
          <% end %>
          <br/>
        <% end %>

         <%= f.submit "Edit meeting", class: "btn btn-large btn-primary" %>
       <% end %>
  </div>
</div>

app/views/meetings/new.html.erb
<% provide(:title, 'New Meeting') %>
<h1>Create meeting</h1>

<div class="row">
  <div class="span6 offset3">

      <%= form_for([@meeting]) do |f| %>
      <%= render :partial => 'shared/error_messages', :locals => {:object => @meeting} %>

        <div class="test">
          <%= f.label :date %>
          <%= f.text_field :date, :value => Date.today, class: "date-picker" %>
          <%= f.label :time %>
          <%= f.text_field :time %>
          <%= f.check_box :public_hearing %>
          Public hearing
        </div>

        <% @sites.each do |site| %>
          <span><%= site.name %></span><br/>
          <% site.rooms.each do |room| %>
            <%= f.radio_button :room_id, room.id %> <%= room.name %><br/>
          <% end %>
        <% end %>

<%#      <%= f.fields_for :committee_meetings do |ff| %>
<%#        <%= ff.label :committee_id %>
<%#        <%= ff.text_field :committee_id %>
<%#      <% end %>

<%# This version creates a parameters array with errors. %>
<%#      <% @committees.each_with_index do |committee,idx| %>
<%#         <%= check_box_tag( "meeting[committee_meetings_attributes][#{idx}][committee_id]",committee.id) %>
<%#         <%= committee.name %>
<%#         <br/>
<%#       <% end %>
        <span>Select a committee or committees for the meeting.</span><br/>
        <% for committee in @committees.each %>
          <% if @committee && (committee.id == @committee.id) %>
            <%= hidden_field_tag( "[has_committee]", @committee.id) %>
            <%= hidden_field_tag( "[committee_meetings_attributes][]", committee.id) %>
            <%= check_box_tag( "[committee_meetings_attributes][]", committee.id, true, :disabled => true) %> 
            <%= committee.name %>
          <% else %>
            <%= check_box_tag( "[committee_meetings_attributes][]", committee.id) %>
            <%= committee.name %>
          <% end %>
          <br/>
        <% end %>

         <%= f.submit "New meeting", class: "btn btn-large btn-primary" %>
       <% end %>
  </div>
</div>

app/views/meetings/public_hearing_notice.html.erb
<% provide(:title, @meeting.date) %>
<div class ="noprint"> <%= link_to "Back to meeting page", meeting_path(@meeting) %></div>
<div class ="title" style="text-align:center;font-weight:bold; padding-bottom:20px; width:800px;">
	<div>City of Newton</div>
        <div class ="title">Legal Notice</div>
        <div><%= @meeting.date.strftime("%A, %B %-d, %Y") %></div>
      </div>
      <div  style="width:800px;padding-bottom:20px;">Public hearings will be held on <%= @meeting.date.strftime("%A, %B %-d, %Y") %> at <%= @meeting.time.strftime("%l:%M %p")  %>, in <%= @meeting.room.name %>, <%= @meeting.room.floor %>, <%= @meeting.room.site.name %>, before the <%= @meeting.committee_names_string %> for the purpose of hearing the following petitions, at which time all parties interested in these items shall be heard. Notice will be published <%= @meeting.notice.publication %>, with a copy posted online at www.ci.newton.ma.us and in a conspicuous place at Newton City Hall.</div>
<div style="width:800px;padding-bottom:20px;">
  <%= render @meeting.public_hearing_item_meetings %>
</div>
<% if @meeting.agenda_submissions.count >1 %>
  <div style="width:800px;padding-bottom:20px;">
    <div style="padding-bottom:20px;">Respectfully submitted,</div>
    <div><%= Person.find(@meeting.agenda_submissions.last.statuser_id).name %></div>
  </div>
<% end %>
<div style="width:800px;float:left">The location of this meeting is handicap accessible, and reasonable accommodations will be provided to persons requiring assistance. If you have a special accommodation need, please contact the Newton ADA Coordinator Trisha Guditz, 617 796-1156, via email at <a href="mailto:tguditz@newtonma.gov">TGuditz@newtonma.gov</a> or via TDD/TTY at 617 796-1089 at least two days in advance of the meeting date.</div>          

app/views/meetings/report.html.erb
<% provide(:title, @meeting.date) %>
<div class ="noprint"> <%= link_to "Back to meeting page", meeting_path(@meeting) %></div>
<div class ="title" style="width:800px; text-align:center;font-weight:bold; padding-bottom:20px;">
	<div>City of Newton</div>
<div class ="title">In Board of Alderman</div>
<div><%= @meeting.committee_names_string %> Report </div>
<div><%= @meeting.date.strftime("%A, %B %-d, %Y") %></div>
</div>
<div style="width:800px;padding-bottom:20px;>    
    	<% if @meeting.action_meetings.any? %>
            <%= render @meeting.action_meetings.order('position ASC') %>
        <% else %>
            No report yet.
        <% end %> 
</div>
<% if @meeting.agenda_submissions.count >1 %>
  <div style="width:800px;padding-bottom:20px;">
    <div style="padding-bottom:20px;">Respectfully submitted,</div>
    <div><%= Person.find(@meeting.agenda_submissions.last.statuser_id).name %></div>
  </div>
<% end %>

app/views/meetings/show.html.erb
<% provide(:title, @meeting.name + " Meeting") %>
<div class="row">
  <aside class="span4">
  <section>
  <h1>
    <% if @meeting.public_hearing %>
      Public Hearing/Meeting: <%= @meeting.date.strftime("%m/%d/%y") %>
    <% else %>
      Meeting: <%= @meeting.date.strftime("%m/%d/%y") %>
    <% end %>
    </h1>
  <% if @meeting.committees %>
    <% @meeting.committees.each do |committee| %>
      <div class="content"><%= link_to committee.name, committee_path(committee) %><%# | 
        <%#               <%= link_to "Remove", destroy_meeting_committee_path(@meeting, committee) %>	
      </div>
    <% end %>
  <% end %>         
  <span><%= @meeting.time.strftime("%l:%M %p") %> </span>
  <span><%= @meeting.room.name %> (<%= @meeting.room.floor %>)</span>
  <span><%= link_to @meeting.site.name, site_path(@meeting.site) %></span>
  <span><%= @meeting.site.address1 %></span>
  <% if @meeting.site.address2? %>
    <span>test<%= @meeting.site.address2 %></span></br>
  <% end %>
  <span><%= @meeting.site.city %>, <%= @meeting.site.state %> <%=@meeting.site.postal %></span>
  <span class="timestamp">Created by <%= @meeting.creator.name %> on <%= @meeting.created_at.strftime("%m/%d/%y") %></span>
  <span class="timestamp">Last updated by <%= @meeting.updater.name %> on <%= @meeting.updated_at.strftime("%m/%d/%y") %></span>         
  <% if current_user && current_user.admin? %>
    <div> <%= link_to "Edit", edit_meeting_path(@meeting)%></div>
    <% if @meeting.public_hearing %>
      <% if @meeting.notice %>
        <div>Notice of the public hearing will be published <%= @meeting.notice.publication %>, with a copy posted online at www.ci.newton.ma.us and in a conspicuous place at Newton City Hall.</div>
         <div><%= link_to "Edit", edit_meeting_notice_path(@meeting, @meeting.notice) %></div>
       <% else %>
         <%= link_to "Create public hearing notice publication information", new_meeting_notice_path(@meeting) %>
       <% end %>
     <% end %>
   <% end %>
  </section>
  </aside>
  <div class="span8">
    <ul class="nav nav-tabs">
     <% if @meeting.date < Date.today %>
      <li class="active"><a href="#actions" data-toggle="tab">Report</a></li>
      <li><a href="#items" data-toggle="tab">Agenda&nbsp;(<%= @meeting.items.count %> items)</a></li>
     <% else %>
       <li class="active"><a href="#items" data-toggle="tab">Agenda&nbsp;(<%= @meeting.item_meetings.count %> items)</a></li>
      <% end %>
       <li><a href="#documents" data-toggle="tab">Documents&nbsp;(<%= @meeting.attachments.count %>)</a></li>
      <li><a href="#activities" data-toggle="tab">Activities</a></li>
    </ul>
    <div class="tab-content">
     <% if @meeting.date < Date.today %>
       <div class="tab-pane" id="items">
     <% else %>
       <div class="tab-pane active" id="items">
     <% end %>
          <div style="padding-bottom:20px;">
            <%= link_to "Print agenda", meeting_agenda_path(@meeting) %>
            <% if @meeting.public_hearing %>
              | <%= link_to "Print public hearing notice", meeting_public_hearing_notice_path(@meeting) %>
            <% end %>
        <% if current_user && current_user.admin? %>

          | <%= link_to "Add an item to meeting", new_meeting_item_meeting_path(@meeting)%>
          | <%= link_to "Create agenda text", new_meeting_meeting_text_path(@meeting, :kind => 'Agenda') %>
          <% if @meeting.agenda_submissions.count < 1 %>
            | <%= link_to "Submit agenda", new_meeting_status_path(@meeting, :new_code => 1, :kind => 'Agenda') %>
          <% else %>
            | Agenda submitted
          <% end %>
        <% end %>
          </div>
        <% if @meeting.item_meetings.any? %>
          <ol id="item_meetings" class="microposts">
            <%= render @meeting.item_meetings.order('position ASC') %>
          </ol>
        <% else %>
          <ol class="microposts">
            <li>
              <% if current_user && current_user.admin? %>
                <span class="content">There are no items on the meeting agenda.  <%= link_to "Add an item to this meeting", new_meeting_item_meeting_path(@meeting)%>
 or navigate to an item and add it to this meeting.</span>
              <% else %>
                <span class="content">There are no items on the meeting agenda.</span>
              <% end %>
            </li>
          </ol>    
        <% end %>
        <% if @meeting.agenda_submissions.count >0 %>
          <div>Agenda submitted by <%= Person.find(@meeting.agenda_submissions.last.statuser_id).name %> on <%= @meeting.agenda_submissions.last.as_of.strftime("%m/%d/%y") %>. </div>
        <%end %>
      </div>
     <% if @meeting.date < Date.today %>
       <div class="tab-pane active" id="actions">
     <% else %>
       <div class="tab-pane" id="actions">
     <% end %>
          <div style="padding-bottom:20px;">
            <%= link_to "Print report", meeting_report_path(@meeting) %>
        <% if current_user && current_user.admin? %>
           <% if !@meeting.attendance_text %>
             | <%= link_to "Add attendance", new_meeting_attendance_text_path(@meeting)%>
           <% else %>
             | <%= link_to "Edit attendance", edit_meeting_attendance_text_path(@meeting, @meeting.attendance_text)%>
           <% end %>
             | <%= link_to "Create report text", new_meeting_meeting_text_path(@meeting, :kind => 'Report') %>
          <% if @meeting.report_submissions.count < 1 %>
            | <%= link_to "Submit report", new_meeting_status_path(@meeting, :new_code => 2, :kind => 'Report') %>
          <% else %>
            | Report submitted
          <% end %>
        <% end %>
      </div>
        <% if @meeting.action_meetings.any? %>
          <ol id="action_meetings" class="microposts">
            <%= render @meeting.action_meetings.order('position ASC') %>
          </ol>            
        <% end %>
        <% if @meeting.items_without_actions.any? %>
          <div>The following item(s) on the agenda have no actions reported:</div>
          <% for item in @meeting.items_without_actions %>
            <div><%= link_to "#"+ item.name, item_path(item.id) %>
              <% if current_user && current_user.admin? %>
	         &nbsp;|&nbsp;<%= link_to "Add an action", 
		     new_meeting_aktion_path(@meeting)+"?agendable_type=item&agendable_id="+item.id.to_s %>
              <% end %>
            </div>
          <% end %>
        <% end %> 
        <% if @meeting.report_submissions.count > 0 %>
          <div>Report submitted by <%= Person.find(@meeting.report_submissions.last.statuser_id).name %> on <%= @meeting.report_submissions.last.as_of.strftime("%m/%d/%y") %>. </div>
        <% end %>
      </div>
      <div class="tab-pane" id="documents"> 
        <ol class="microposts">
          <% if @parent.documents.any? %>
            <%= render @meeting.documents %>
            <% if current_user && current_user.admin? %>
              <span class="content"><%= link_to "Upload a document", polymorphic_path([@parent, :document], :action => :new) %>.</span>
            <% end %>
          <% else %>
            <li>
            <span class="content">There are no documents associated with this <%= @parent.class.name.downcase %>. 
              <% if current_user && current_user.admin? %>
                <%= link_to "Upload a document", 
                  polymorphic_path([@parent, :document], :action => :new)   %>.
                <% end %>
              </span>
              </li>
            <% end %>
          </ol>
        </div>

        <div class="tab-pane" id="activities">
  
          <% if @meeting.activities.any? %>
            <ol class="microposts">
              <%= render @meeting.activities %>
            </ol>
          <% else %>
            Reserved for actions
          <% end %>
        </div>


      </div>
    </div>
  </div>
  <script>  $(function () {
    $('#myTab a:last').tab('show');
  })
</script>
<script type="text/javascript">
  $(function() {
      $("#item_meetings").sortable({items:'.item_meeting', handle:'.handle', axis:'y', cursor: 'move', update: function(){
        $.get('/item_meetings/reorder?meeting='+<%= @meeting.id %>, $(this).sortable('serialize'));
        }});
      });
  $(function() {
      $("#action_meetings").sortable({items:'.action_meeting', handle:'.handle2', axis:'y', cursor: 'move', update: function(){
        $.get('/action_meetings/reorder?meeting='+<%= @meeting.id %>, $(this).sortable('serialize'));
        }});
      });

$('.toggle').click(function() {
  var content = $(this).next();
  $(content).toggle();
  $(content).next().toggle(); 
  return false;
});</script>