config/routes.rb
OpenDocket::Application.routes.draw do

  get "activities/new"

  get "notices/new"

  get "submissions/new"

  get "action_item_meeting/new"

  get "action_meetings/new"

  get "attendance_texts/new"

  resources :people do
    resources :memberships
  end
  
  get "meeting_texts/new"

  get "statuses/new"

  get "user/new"

  get "status/new"

  get "attachments/new"

  resources :aktions 

  resources :memberships

  resources :notices

  resources :items do 
    resources :activities
    resources :dockets
    resources :documents
    resources :item_meetings
    resources :statuses
  end
 
  resources :committees do
    resources :dockets
    resources :meetings
    resources :memberships
  end

  resources :documents do
    resources :attachments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites do
    resources :rooms
  end

  resources :meetings do
    resources :aktions
    resources :attendance_texts
    resources :committee_meetings
    resources :documents
    resources :item_meetings
    resources :meeting_texts
    resources :notices
    resources :statuses
  end

  resources :dockets do
    resources :statuses
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/committees/:id/edit' => 'committees#edit', :via => :post
  match '/items/:id/edit' => 'items#edit', :via => :post
  match '/meetings/:id/agenda' => 'meetings#agenda', :as => 'meeting_agenda', :via => :get
  match '/meetings/:id/public_hearing_notice' => 'meetings#public_hearing_notice', :as => 'meeting_public_hearing_notice', :via => :get
  match '/meetings/:id/report' => 'meetings#report', :as => 'meeting_report', :via => :get  
 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'item_meetings/reorder' => 'item_meetings#reorder', :as => 'item_meetings_reorder', :via => :get
  match 'action_meetings/reorder' => 'action_meetings#reorder', :as => 'action_meetings_reorder', :via => :get

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id           :integer          not null, primary key
#  doc_type     :string(255)
#  name         :string(255)
#  description  :string(255)
#  submitted_by :string(255)
#  creator_id   :integer
#  updater_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  URL          :string(255)
#  submitted_on :date
#

class Document < ActiveRecord::Base
  attr_accessible :description, :doc_type, :name, :submitted_by, :submitted_on, :URL, :attachments_attributes

  has_many :attachments 
  has_many :owners, :through => :attachments

  accepts_nested_attributes_for :attachments 

  belongs_to :creator,     :class_name => 'User'
  belongs_to :updater,     :class_name => 'User'

  validates :URL, presence: true

  has_many :activity_logs, :as => :owner
  has_many :activities, :through => :activity_logs, :as => :owner


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update]
  before_filter :admin_user,     only: [:new, :create, :edit, :update]
  before_filter :get_parent # Defined in ApplicationController

  def new
    if @parent.class.name == "Meeting"
      @item_meetings = @parent.item_meetings
    end
    @document = Document.new
    @document.submitted_on = Date.today
#    render :template => @template_prefix + 'new'
  end

  def create
  
    @document = Document.new(params[:document])
    if @document.name == ""
      @document.name = @document.URL
    end
    if @parent.class.name == "Meeting"
      @item_meetings = @parent.item_meetings
    end
    @attachments = params[:item_attachments_attributes]
    @document.creator_id = current_user.id
    @document.updater_id = current_user.id

    if @document.save
      @activity1 = Activity.create(
                :message => "Document #{@document.name} uploaded into Open Docket",
                :activity_type => "DocumentUploaded", :date_actual => Date.today)
      ActivityLog.create(:activity_id => @activity1.id, :owner_type => "Document", :owner_id => @document.id) 

      if @document.attachments.build(:owner_type => @parent.class.name, :owner_id => @parent.id).save
          @activity2 = Activity.create(
                :message => "Document #{@document.name} attached to #{@parent.class.name} #{@parent.name}.",
                :activity_type => "DocumentAttachment", :date_actual => Date.today)
          ActivityLog.create(:activity_id => @activity2.id, :owner_type => "Document", :owner_id => @document.id) 
          ActivityLog.create(:activity_id => @activity2.id, :owner_type => @parent.class.name, :owner_id => @parent.id)   

        if @attachments
          for attachment in @attachments.each do
            @document.attachments.build(:owner_type => "Item", :owner_id => attachment).save
            @activity3 = Activity.create(
                :message => "Document #{@document.name} attached to Item {Item.find_by_id(attachment).name}.",
                :activity_type => "DocumentAttachment", :date_actual => Date.today)
            ActivityLog.create(:activity_id => @activity3.id, :owner_type => "Document", :owner_id => @document.id) 
            ActivityLog.create(:activity_id => @activity3.id, :owner_type => "Item", :owner_id => attachment)              
          end
        end
        flash[:success] = "You have succesfully uploaded document #{@document.name} to #{@parent.class.name.downcase} #{@parent.name}"
        redirect_to @parent


      else
        @document.destroy
        render 'new'
      end

    else
      render 'new'
    end

  end

  def show
    @document = Document.find_by_id(params[:id])
    @attachedto = @document.attachments.collect
    @activities = @document.activities
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<% attachment = document.attachments.find_by_owner_id(@parent.id) %>
<li>
  <span class="content">
    <%= link_to document.name, document.URL %>&nbsp;|&nbsp;<%= link_to "Details", document_path(document.id) %>
  </span>
  <span class="timestamp">
    Uploaded <%= document.created_at.strftime("%m/%d/%y") %>
      <% if current_user && current_user.admin? %>
        &nbsp;|&nbsp;<%= link_to "Remove", [document, attachment], method: :delete,
         data: { confirm: "You sure?" },
         title: "Title" %>
      <% end %>
  </span>
</li>
   

app/views/documents/new.html.erb
<% provide(:title, 'Upload Document') %>
<h1>Upload document</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for([@parent, @document]) do |f| %>
    <%= render :partial => 'shared/error_messages', :locals => {:object => @document} %>
	
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :URL %>
      <%= f.text_field :URL %>

      <%= f.label :submitted_on %>
      <%= f.text_field :submitted_on, :value => Date.today, class: "date-picker" %>

      <%= f.label :submitted_by %>
      <%= f.text_field :submitted_by %>
            
      <%= f.label :doc_type %>
      <%= f.text_field :doc_type %>

      <%= f.label :description %>
      <%= f.text_area :description, :size => "60x12" %>

<%#      <% @items.each_with_index do |item,idx| %>
<%#         <%= check_box_tag( "document[attachments_attributes][#{idx}][owner_id]",item.id) %>
<%#         <%= item.name %>
<%#         <br/>
<%#       <% end %>
      <% if @item_meetings %>
        <% for item_meeting in @item_meetings.all %>
          <% if item_meeting.agendable_type == "Item" %>
          <%= check_box_tag( "[item_attachments_attributes][]", item_meeting.agendable_id) %>
          <%= item_meeting.agendable.name %>
          <br/>
        <% end %>
       <% end %>
     <% end %>

      <%= f.submit "Upload document", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/documents/show.html.erb
<% provide(:title, @document.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @document.name %>
      </h1>
      <span>URL</span>
      <span> <%= link_to @document.URL, @document.URL %></span>
      <span>Submitted on</span>
      <span><%= @document.submitted_on.strftime("%m/%d/%y") %></span>
      <span>Submitted by</span>
      <span><%= @document.submitted_by %></span>
      <% if @document.description? %>
        <span>Description</span>
        <span><%= @document.description %></span>
      <% end %>
      <span class="timestamp">Created by <%= @document.creator.name %> on <%= @document.created_at.strftime("%m/%d/%y") %></span>
      <span class="timestamp">Last updated by <%= @document.updater.name %> on <%= @document.updated_at.strftime("%m/%d/%y") %></span>
      <% if current_user && current_user.admin? %>
        <span> <%= link_to "Edit", edit_document_path(@document)%>.
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#owners" data-toggle="tab">Attached to</a></li>
      <li><a href="#activity" data-toggle="tab">Activity</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="owners">
         <% for attachedto in @attachedto.each %>
           <%= attachedto.owner.class.name %>: <%= link_to attachedto.owner.name, polymorphic_path([attachedto.owner]) %><br/>
         <% end %>
      </div>
      <div class="tab-pane" id="activity">
       <% if @document.activities.any? %>
         <%= render @activities %>
       <% else %>
         Reserved for actions
       <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(function () {
    $('#myTab a:last').tab('show');
  })
</script>