config/routes.rb
OpenDocket::Application.routes.draw do

  get "activities/new"

  get "notices/new"

  get "submissions/new"

  get "action_item_meeting/new"

  get "action_meetings/new"

  get "attendance_texts/new"

  resources :people do
    resources :memberships
  end
  
  get "meeting_texts/new"

  get "statuses/new"

  get "user/new"

  get "status/new"

  get "attachments/new"

  resources :aktions 

  resources :memberships

  resources :notices

  resources :items do 
    resources :activities
    resources :dockets
    resources :documents
    resources :item_meetings
    resources :statuses
  end
 
  resources :committees do
    resources :dockets
    resources :meetings
    resources :memberships
  end

  resources :documents do
    resources :attachments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites do
    resources :rooms
  end

  resources :meetings do
    resources :aktions
    resources :attendance_texts
    resources :committee_meetings
    resources :documents
    resources :item_meetings
    resources :meeting_texts
    resources :notices
    resources :statuses
  end

  resources :dockets do
    resources :statuses
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/committees/:id/edit' => 'committees#edit', :via => :post
  match '/items/:id/edit' => 'items#edit', :via => :post
  match '/meetings/:id/agenda' => 'meetings#agenda', :as => 'meeting_agenda', :via => :get
  match '/meetings/:id/public_hearing_notice' => 'meetings#public_hearing_notice', :as => 'meeting_public_hearing_notice', :via => :get
  match '/meetings/:id/report' => 'meetings#report', :as => 'meeting_report', :via => :get  
 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'item_meetings/reorder' => 'item_meetings#reorder', :as => 'item_meetings_reorder', :via => :get
  match 'action_meetings/reorder' => 'action_meetings#reorder', :as => 'action_meetings_reorder', :via => :get

end

app/models/committee.rb
# == Schema Information
#
# Table name: committees
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  shortname   :string(255)
#  creator_id  :integer
#  updater_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Committee < ActiveRecord::Base
  attr_accessible :creator_id, :description, :name, :shortname, :updater_id, :item_id, :note

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :creator_id, presence: true

  belongs_to :creator, :class_name => 'User'
  belongs_to :updater, :class_name => 'User'

  has_many :committee_meetings
  has_many :meetings, through: :committee_meetings

  has_many :dockets
  has_many :items, through: :dockets, source: :item

  has_many :activity_logs, :as => :owner
  has_many :activities, :through => :activity_logs, :as => :owner

  has_many :memberships
  has_many :people, through: :memberships, source: :person

  def ondocket?(item)
    dockets.find_by_item_id(item.id)
  end

  def ondocket!(item, note)
    dockets.create!(item_id: item.id, note: note)
    #create activities (on docket item and committee)
  end

  def undocket!(item)
    dockets.find_by_item_id(item.id).destroy
    #create activities (on docket item and committee)
  end

  def upcomingmeetings
    meetings.all.select { |v| v.date > Date.today}
  end

  def nextmeeting
    upcomingmeetings.sort_by do |d|
      d.date
    end
    upcomingmeetings.first
  end

  def memberships_current
    memberships.select{|x| x['term_end'] == nil}.sort_by{|e| e['position']}
  end

   def memberships_past
    memberships.select{|x| x['term_end'] != nil}
  end

   def members_names_string
    memberships_current.collect { |id| Membership.find_by_id(id).display_as }.join(', ') 
  end

  
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit, :update]
  before_filter :admin_user,     only: [:new, :create, :edit, :update]

 def create
    @committee = Committee.new(params[:committee])
    @committee.creator_id = current_user.id
    @committee.updater_id = current_user.id

    if @committee.save
      @activity = Activity.create(
                :message => "Added #{@committee.name} to Open Docket.",
                :activity_type => "NewCommittee", :date_actual => @committee.created_at)
      ActivityLog.create(:activity_id => @activity.id, :owner_type => "Committee", :owner_id => @committee.id)
      flash[:success] = "You have succesfully created #{@committee.name}!"
      redirect_to @committee
    else
      render 'new'
    end
  end

  def edit
     @committee = Committee.find(params[:id])
  end

  def update
    @committee = Committee.find(params[:id])
    @committee.updater_id = current_user.id
    if @committee.update_attributes(params[:committee])
      flash[:success] = "Committee updated"
      redirect_to @committee
    else
      render 'edit'
    end
  end

  def show
    @committee = Committee.find(params[:id])
    @activities = @committee.activities
    if @committee.dockets.count > 0
      @dockets = @committee.dockets
      @agingaverage = @dockets.collect(&:age).inject(:+)/@dockets.size
    end
    @meetings = @committee.meetings
   end

  def new
    @committee = Committee.new
  end

  def index
    @committees = Committee.all
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_committees.html.erb
<li>
  <span class="content"><%= docket.item.number %></span> |
  <span class="timestamp">
    Created <%= docket.created_at.strftime("%m/%d/%y") %>
  </span>
</li>

app/views/committees/_dockets.html.erb
<li>
<li>
  <span class="content"><%= docket.id %></span>
  <span class="timestamp">
    Created <%= docket.created_at %>
  </span>
</li>

app/views/committees/_items.html.erb
<li>
<li>
  <span class="content"><%= docket.item.number %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(docket.created_at) %> ago.
  </span>
</li>

app/views/committees/edit.html.erb
<% provide(:title, "Edit committee") %> 
<h1>Edit committee</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@committee) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :shortname %>
      <%= f.text_field :shortname %>

      <%= f.label :description %>
      <%= f.text_area :description, :size => "60x12" %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/committees/index.html.erb
<% provide(:title, 'Committees') %>
<h1>Committees</h1>

<ul class="committees">
  <% @committees.each do |committee| %>
    <li>
      <%= link_to committee.name, committee %>
      <% if current_user && current_user.admin? %>
        | <%= link_to "edit", edit_committee_path(committee.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/committees/new.html.erb
<% provide(:title, 'New') %>
<h1>New Committee</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@committee) do |f| %>
	
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :shortname %>
      <%= f.text_field :shortname %>

      <%= f.label :description %>
      <%= f.text_area :description, :size => "60x12" %>

      <%= f.submit "Create committee", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/committees/show.html.erb
<% provide(:title, @committee.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @committee.name %>
      </h1>
      <span><%= @committee.description %></span>
      <span class="timestamp">Created by <%= @committee.creator.name %> on <%= @committee.created_at.strftime("%m/%d/%y") %></span>
      <span class="timestamp">Last updated by <%= @committee.updater.name %> on <%= @committee.updated_at.strftime("%m/%d/%y") %></span>
    </section>
  </aside>
  <div class="span8">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#meetings" data-toggle="tab">Meetings</a></li>
      <li><a href="#items" data-toggle="tab">Items&nbsp;(<%= @committee.dockets.count %>)</a></li>
      <li><a href="#members" data-toggle="tab">Members</a></li>
      <li><a href="#activities" data-toggle="tab">Activities</a></li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="meetings">
        <% if @committee.meetings.any? %>
          <ol class="microposts">
            <%= render @meetings %>
          </ol>
          <% if current_user && current_user.admin? %>
            <span class="content"><%= link_to "Create another meeting", new_committee_meeting_path(@committee)%>.</span>
          <% end %>
        <% else %>
          <ol class="microposts">
            <li>
              There are no meetings scheduled for this committee.
            </li>
          </ol>    
        <% end %> 
      </div>

      <div class="tab-pane" id="items">
        <% if @committee.dockets.any? %>
          <span class="content">Days on docket in parantheses.</span>
          <span class="content">Average days on docket for current items: <%= @agingaverage %></span>
          <ol class="microposts">
            <%= render @dockets %>
          </ol>
        <% else %>
          <ol class="microposts">
            <li>
              There are no items on the docket. Navigate to an item to add it to this docket.
            </li>
          </ol>    
        <% end %> 
      </div>

     <div class="tab-pane" id="members">
              <% if @committee.memberships.any? %>
 <!--                 <span class="content">
                    Current members
                  </span>
-->
                <ol class="microposts">
                  <%= render @committee.memberships_current %>
                </ol>
<!--                  <span class="content">
	            Past members
                  </span>
                  -->
                  <ol class="microposts">
                    <%= render @committee.memberships_past %>
                  </ol>
              <% else %>
                Reserved for members
              <% end %>
      </div>

      
     <div class="tab-pane" id="activities">
         <% if @committee.activities.any? %>
           <ol class="microposts">
             <%= render @activities %>
           </ol>
         <% else %>
           Reserved for actions
         <% end %>
      </div>


    </div>

  </div>

</div>
<script>  $(function () {
    $('#myTab a:last').tab('show');
  })
</script>
<script type="text/javascript">
$('.toggle').click(function() {
  var content = $(this).next();
  $(content).toggle();
  $(content).next().toggle(); 
  return false;
});</script>